### ISSUE TITLE
Getting "No client id supplied" exception

### ISSUE THREAD

**Issue by nandinicbit1981** [SequencingDOTcom/OAuth2-code-with-demo#2]
Hello,
I am trying to get the oauth flow working in my android app.
I followed the code snippet that is provided in this demo app, but i am getting an exception
 {"error":"invalid_client","error_description":"No client id supplied"}

Here are the steps to recreate:

1) I get the login screen when i launch the app
2) i registered for an account, and then i login.
3) in the onloadresource method in "OauthWebViewClient" class, 
    - first iteration: url = authapp://Default/Authcallback, but its not authorized, so it goes into the first if loop,  
             if (null == Uri.parse(url).getQueryParameter("code")) {
                    // We just being the oauth2 authorization loop. So we redirect the client to
                    // Sequencing website and ask the user to allow our app to use his data.
                    view.loadUrl(getOauth().getLoginRedirectUrl());
                    System.out.println(getOauth().getLoginRedirectUrl());

                } 
   ;
    -second iteration : url = https://sequencing.com/oauth2/authorize?[scope=demo,%20state=99cefce0cac5d2235fe9a6a4cf9d2e36,%20response_type=code,%20client_id=something,%20redirect_uri=authapp://Default/Authcallback]

 - third iteration : https://sequencing.com/favicon.ico [This is when i get the exception saying no client id.]

I even tried to add the client id , but it doesn't work. Do i need to make any more changes to the code than what is present in this demo code?

Please help.

**Comment by BrandonColbyMD** [comment]
Hi @nandinicbit1981,

Thank you for reporting this issue. Our API team is currently reviewing and will provide a response asap.

Thank you,
Brandon
Sequencing.com

**Comment by nandinicbit1981** [comment]
In addition to above error, I was also getting an exception saying javascript was not enabled on my android browser, eventhough i had the setting enabled.

I had to add the following line of code  to the oncreate method in LoginSequenceActivity class.

  myWebView.getSettings().setJavaScriptEnabled(true);

**Comment by nandinicbit1981** [comment]
@BrandonColbyMD any updates on this issue?
I will be participating in the HackGenome on april 6th. This codebase is listed as a source for the OAuth for the same. Please let us know when this issue can be resolved.

**Comment by BrandonColbyMD** [comment]
Hi @nandinicbit1981 - the API team has identified the issues and will be updating the repo today with the fixes.

**Fix that will be deployed today: update oauth2-core library to version 1.7**
* will resolve all issues you identified
* previous version has corrupted redirect url, new version will resolve the javascript exception

Thank you for alerting us to these issues. I will ping you once this repo has been updated today.

Thank you,
Brandon
Sequencing.com

**Comment by ksyuOk** [comment]
Hi @nandinicbit1981 
Please see, project's sources have been updated. 
Just notice, that you can also use sequencing android-oauth library instead of project source code, by adding dependency in your project: compile 'com.sequencing:android-oauth:1.0.22'.

See also example in Android-Master-Plugin-Plug-N-Play-Sample. [https://github.com/SequencingDOTcom/Android-Master-Plugin-Plug-N-Play-Sample]

**Comment by BrandonColbyMD** [comment]
Hi @nandinicbit1981 - please review the update provided above and let us know if you have any further questions. We're here to help so please reach out to us at any time. We also look forward to meeting you at the Microsoft-Sequencing.com Hackathon in a few days!

If we don't hear back from you by tomorrow (April 4) at 5p PT then we'll consider this issue resolved.

Thank you,
Brandon
Sequencing.com

**Comment by nandinicbit1981** [comment]
@BrandonColbyMD @ksyuOk Thankyou both for a timely response.The issue is now resolved.
Really appreciate your help.
